Repository dsc-sookmyung/2022-G.Ipsa-SolutionChallenge, pull requests merged in 2022-03, with the labels that each got.

#7 style, param type define
  frontend/GIpsa/src/navigator/types.ts
  frontend/GIpsa/src/screens/Main/CreateScreen/index.tsx
  frontend/GIpsa/src/screens/Main/HomeScreen.tsx
  frontend/GIpsa/src/screens/Main/HomeScreen/Styles.ts
  frontend/GIpsa/src/screens/Main/HomeScreen/index.tsx
  frontend/GIpsa/src/screens/Main/ProfileScreen/index.tsx
  frontend/GIpsa/src/screens/Main/SearchScreen/index.tsx
  frontend/GIpsa/src/screens/Sign/LoginScreen/index.tsx
Labels: review

#4 Node/swagger initialize
  backend/.gitignore
  backend/README.md
  backend/build/swagger.yaml
  backend/dist/app.js
  backend/dist/controllers/TodosController.js
  backend/dist/controllers/UserInfoController.js
  backend/dist/database/dbconnector.js
  backend/dist/database/entities/Comment.js
  backend/dist/database/entities/Follow.js
  backend/dist/database/entities/Like.js
  backend/dist/database/entities/Story.js
  backend/dist/database/entities/UserInfo.js
  backend/dist/database/entities/post.js
  backend/dist/repository/postRepository.js
  backend/dist/repository/userInfoRepository.js
  backend/dist/routers/TodosRouter.js
  backend/dist/routers/UserInfoRouter.js
  backend/dist/server.js
  backend/package.json
  backend/src/app.ts
  backend/src/database/dbconnector.ts
  backend/src/database/entities/Comment.ts
  backend/src/database/entities/Follow.ts
  backend/src/database/entities/Like.ts
  backend/src/database/entities/Story.ts
  backend/src/database/entities/UserInfo.ts
  backend/src/routers/UserInfoRouter.ts
  backend/src/server.ts
  backend/src/swagger/openapi.yaml
  backend/tsconfig.json
  backend/yarn.lock
Labels: feat

#16 Building router
  backend/.gcloudignore
  backend/.gitignore
  backend/app.yaml
  backend/build/swagger.yaml
  backend/dist/app.js
  backend/dist/database/dbconnector.js
  backend/dist/database/entities/Comment.js
  backend/dist/database/entities/Follow.js
  backend/dist/database/entities/Like.js
  backend/dist/database/entities/Story.js
  backend/dist/database/entities/UserInfo.js
  backend/dist/routers/StoryRouter.js
  backend/dist/routers/UserInfoRouter.js
  backend/dist/server.js
  backend/package.json
  backend/src/database/dbconnector.ts
  backend/src/database/entities/Comment.ts
  backend/src/database/entities/Follow.ts
  backend/src/database/entities/LikeEntity.ts
  backend/src/database/entities/UserInfo.ts
  backend/src/routers/CommentRouter.ts
  backend/src/routers/FollowRouter.ts
  backend/src/routers/LikeRouter.ts
  backend/src/routers/StoryRouter.ts
  backend/src/routers/UserInfoRouter.ts
  backend/src/server.ts
  backend/src/swagger/openapi.yaml
  g.ipsa-diagram
Labels: feat

#28 Upload file
  backend/.gcloudignore
  backend/.gitignore
  backend/dist/config/Storage.js
  backend/dist/config/UploadImage.js
  backend/dist/database/dbconnector.js
  backend/dist/database/entities/Comment.js
  backend/dist/database/entities/Follow.js
  backend/dist/database/entities/LikeEntity.js
  backend/dist/routers/CommentRouter.js
  backend/dist/routers/FollowRouter.js
  backend/dist/routers/LikeRouter.js
  backend/dist/routers/StoryRouter.js
  backend/dist/routers/UserInfoRouter.js
  backend/dist/server.js
  backend/package.json
  backend/src/config/Storage.ts
  backend/src/config/UploadImage.ts
  backend/src/routers/CommentRouter.ts
  backend/src/routers/FollowRouter.ts
  backend/src/routers/LikeRouter.ts
  backend/src/routers/StoryRouter.ts
  backend/src/routers/UserInfoRouter.ts
  backend/src/server.ts
  backend/yarn-error.log
  backend/yarn.lock
Labels: feat

#59 Style/#57 player style
  frontend/GIpsa/src/navigator/Main.tsx
  frontend/GIpsa/src/navigator/Profile.tsx
  frontend/GIpsa/src/screens/Main/HomeScreen/index.tsx
  frontend/GIpsa/src/screens/Main/SearchScreen/index.tsx
  frontend/GIpsa/src/shared/components/MusicPlayerModal/Styles.ts
  frontend/GIpsa/src/shared/components/MusicPlayerModal/index.tsx
  frontend/GIpsa/src/shared/components/MyText/index.tsx
  frontend/GIpsa/src/shared/components/PlayingBar/Styles.ts
  frontend/GIpsa/src/shared/components/PlayingBar/index.tsx
  frontend/GIpsa/src/shared/components/StoryCard/index.tsx
  frontend/GIpsa/src/shared/types/story.ts
Labels: style
